# Generated by Django 2.1 on 2019-09-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190903_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_to',
            field=models.ManyToManyField(blank=True, related_name='subscriber', to='accounts.Profile'),
        ),
    ]
