# Generated by Django 2.1 on 2019-09-04 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190903_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_to',
            field=models.ManyToManyField(blank=True, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
