# Generated by Django 2.1 on 2019-09-02 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Picture')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Add time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
